FROM  sonarqube:7.9.2-community
MAINTAINER Jitendra Singh

EXPOSE 9000

ENV SERVICE_NAME="sonarqube"
ENV PLUGIN_FOLDER="/opt/sonarqube/extensions/plugins/"

# Add language plugins
#COPY ./plugins/* $PLUGIN_FOLDER
